### PR TITLE
feat: Qt GUI

### PR DESCRIPTION
**Pull request by potatoeggy**
Attempt 2!

Add a Qt 6 GUI written in Qt Creator and the PySide 6 bindings.

Blocked by https://github.com/potatoeggy/mandown/pull/32. Resolves https://github.com/potatoeggy/mandown/issues/7.

### CODE REVIEW

**Comment by potatoeggy** [comment]
image

**Comment by potatoeggy** [comment]
It looks ugly, is not responsive, chapter selection doesn't work, and there are still a couple of crashes — but it's okay!

**Comment by menelic** [comment]
great - but how to start it? Can't find anything in the docs?

**Comment by potatoeggy** [comment]
Running `mandown-gui` will open the Qt UI. Disclaimer: it's not great though so the CLI is a much better experience.

**Pull request merged**
